services:
  mcp-http-server-node:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile} # Default or override with env var
      target: ${BUILD_TARGET:-} # Optional build target
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      # Core Configuration
      - MCP_CONFIG_FILE=${MCP_CONFIG_FILE:-mcp_servers.config.json}
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-redmine}
      - PORT=${PORT:-3000}
      - HOST=${HOST:-0.0.0.0}

      # Authentication
      - HTTP_API_KEY=${HTTP_API_KEY}
      - DISABLE_AUTH=${DISABLE_AUTH:-false}

      # Node.js Runtime Configuration
      - NODE_PACKAGE_MANAGER=${NODE_PACKAGE_MANAGER:-npm}
      - WORK_DIR=/tmp/mcp-servers

      # Logging
      - RUST_LOG=${RUST_LOG:-info}

      # MCP Server Environment Variables
      - REDMINE_URL=${REDMINE_URL}
      - REDMINE_API_KEY=${REDMINE_API_KEY}
      - REDMINE_HOST=${REDMINE_HOST}

    volumes:
      - mcp_cache:/tmp/mcp-servers:rw
      - npm_cache:/app/.npm-cache:rw

    restart: unless-stopped

volumes:
  mcp_cache:
    driver: local
  npm_cache:
    driver: local
